### ISSUE TITLE
Disable smoothing

### ISSUE THREAD

**Issue by mrdoob** [juj/emscripten-scummvm#12]
Use `ctx.imageSmoothingEnabled = false` to show the pixels in their full glory :)

http://jsfiddle.net/VAXrL/190/

**Comment by juj** [comment]
Hehe, great point! :) Thanks! I'll see about adding this to the next rebuild when I upload fixes to the page.

**Comment by juj** [comment]
I now had a look at this, and disabled imageSmoothingEnabled for the 2D context of the main page canvas, but could not see any visual difference in chrome or firefox. Then it turns out the compositing is controlled slightly separately here.

This page works: http://phrogz.net/tmp/canvas_image_zoom.html
although there's a bug that it won't work on Chrome on Windows: https://code.google.com/p/chromium/issues/detail?id=106662
Other browsers work great.

**Comment by juj** [comment]
Now implemented and uploaded to site. Noticed that IE doesn't do point filtering either.

**Comment by mrdoob** [comment]
I think you implemented the CSS approach. I was suggesting using the canvas approach instead.
This is how the code looks like:

``` javascript
var scale = 4;

// internal canvas

var canvas = document.createElement( 'canvas' );
canvas.width = 160;
canvas.height = 120;

var context = canvas.getContext( '2d' );
context.fillStyle = 'red';
context.fillRect( 0, 0, 320, 240 );
context.fillStyle = 'black';
context.beginPath();
context.arc( 80, 60, 40, 0, Math.PI * 2 );
context.fill();

// screen canvas

var canvas2 = document.createElement( 'canvas' );
canvas2.width = canvas.width * scale;
canvas2.height = canvas.height * scale;

var context = canvas2.getContext( '2d' );
context.imageSmoothingEnabled = false;
context.webkitImageSmoothingEnabled = false;
context.mozImageSmoothingEnabled = false;
context.drawImage( canvas, 0, 0, canvas2.width, canvas2.height );

document.body.appendChild( canvas2 );
```

http://jsfiddle.net/57nSc/
